name: Build and publish Python wheel to pypi

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pypa/build
      run: python3 -mpip install --user build

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/


  publish-to-pypi:
    name: Publish to pypi.org
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [ build ]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/annet

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://pypi.org/legacy/
          verify-metadata: false
